window.i18n = {
    en: {
        site: { title: 'SpaceSwitcher — Control Every Space' },
        hero: { heading: 'SpaceSwitcher', tagline: 'Control Every Space.' },
        quicknav: { page: 'Page', links: 'Links', more: 'More', overview: 'Overview', features: 'Features', install: 'Install', github: 'GitHub', releases: 'Releases', portfolio: 'Portfolio', blog: 'Blog', desktoprenamer: 'DesktopRenamer', optclicker: 'OptClicker' },
        overview: { label: 'Overview', headingHtml: 'Per-space control over your <span class="text-editorial gradient-text">applications and Dock.</span>', bodyHtml: 'Define per-space app rules and custom Dock configurations. Built on <a href="https://desktoprenamer.mqiu.dev" target="_blank" style="color: var(--klein-blue-text);">DesktopRenamer</a>\'s SpaceAPI, it reacts to space changes instantly.' },
        features: { label: 'Features', headingHtml: 'Automate every <span class="text-editorial gradient-text">workspace</span> transition.', slide1num: '01 / Rules', slide1title: 'App Rules <span class="text-editorial gradient-text">Per Space</span>', slide1body: 'Define which apps show, hide, or come to front when you switch spaces. Six action types — from simple show/hide to hotkey simulation.', slide2num: '02 / Docks', slide2title: 'Custom Docks <span class="text-editorial gradient-text">Per Space</span>', slide2body: 'Assign different Dock configurations to different spaces. Add apps, spacers, and reorder items freely.' },
        moreFeatures: { actionTypesLabel: '6 Action Types', actionTypesBody: 'Show, Hide, Minimize, Bring to Front, App Shortcut, and Global Shortcut — chain them into workflows for each space group.', hotkeyLabel: 'Hotkey Simulation', hotkeyBody: 'Trigger app-specific or global keyboard shortcuts when switching spaces — sync in-app workspaces with your macOS spaces automatically.' },
        install: { label: 'Install', headingHtml: 'Get started in <span class="text-editorial" style="color: var(--gold-light); font-style: italic;">seconds.</span>', body: 'macOS 13.0+. Requires DesktopRenamer with SpaceAPI enabled. Drag to Applications, done.', download: 'Download', or: 'or', copy: 'Copy', disclaimer: 'Not signed with a paid Apple Developer account — go to <strong>System Settings → Privacy & Security</strong> if macOS blocks the app. Permissions are guided on first launch.', prerequisite: 'Prerequisite: Install DesktopRenamer first.', downloadDR: 'Download DesktopRenamer', orDR: 'or', copyDR: 'Copy' },
        companions: { label: 'Companions', headingHtml: 'Works great with <span class="text-editorial gradient-text">your</span> toolkit.', desktoprenamerTitle: 'DesktopRenamer', desktoprenamerBody: 'Rename your macOS spaces and enable the SpaceAPI that SpaceSwitcher depends on. The essential companion.', optclickerTitle: 'OptClicker', optclickerBody: 'Right-click with the Option key. A simple utility that complements your macOS workspace workflow.', learnMore: 'Learn More' },
        footer: { copyright: '© 2026 - Michael Qiu.', brand: 'SpaceSwitcher.' },
        sidebar: { home: 'Home', overview: 'Overview', features: 'Features', install: 'Install', companions: 'Companions', github: 'GitHub' },
        sectionLabels: { home: 'Home', overview: 'Overview', features: 'Features', 'more-features': 'Features', install: 'Install', companions: 'Companions' }
    },
    zh: {
        site: { title: 'SpaceSwitcher — 掌控每个桌面' },
        hero: { heading: 'SpaceSwitcher', tagline: '掌控每个桌面。' },
        quicknav: { page: '页面', links: '链接', more: '更多', overview: '概览', features: '功能', install: '安装', github: 'GitHub', releases: '发布', portfolio: '主页', blog: '博客', desktoprenamer: 'DesktopRenamer', optclicker: 'OptClicker' },
        overview: { label: '概览', headingHtml: '分桌面控制 <span class="text-editorial gradient-text"> App 和 程序坞</span>。', bodyHtml: '定义每个桌面的 App 行为规则并自定义程序坞。基于 <a href="https://desktoprenamer.mqiu.dev" target="_blank" style="color: var(--klein-blue-text);">DesktopRenamer</a> 构建，即时响应桌面变化。' },
        features: { label: '功能', headingHtml: '自动化你的每个<span class="text-editorial gradient-text">工作区。</span>', slide1num: '01 / 规则', slide1title: '按<span class="text-editorial gradient-text">桌面</span>设置 App 规则', slide1body: '定义切换桌面时哪些 App 显示、隐藏或置顶。六种操作类型——从简单的显示/隐藏到快捷键模拟。', slide2num: '02 / 程序坞', slide2title: '按<span class="text-editorial gradient-text">桌面</span>自定义程序坞', slide2body: '为不同桌面分配不同程序坞。自由添加 App 、分隔符和重新排序项目。' },
        moreFeatures: { actionTypesLabel: '6 种操作类型', actionTypesBody: '显示、隐藏、最小化、置顶、 App 快捷键和全局快捷键——将它们串联成每个桌面组的工作流。', hotkeyLabel: '快捷键模拟', hotkeyBody: '切换桌面时触发 App 特定或全局键盘快捷键——将 App 内工作区与你的 macOS 桌面自动同步。' },
        install: { label: '安装', headingHtml: '即刻<span class="text-editorial" style="color: var(--gold-light);">开始。</span>', body: 'macOS 13.0+。需要 DesktopRenamer 并启用 SpaceAPI。拖入 Applications 文件夹，完成。', download: '下载', or: '或', copy: '复制', disclaimer: '未使用付费 Apple 开发者账号签名——如果 macOS 阻止该 App ，请前往<strong>系统设置 → 隐私与安全性</strong>。首次启动时会引导完成权限设置。', prerequisite: '前置：请先安装 DesktopRenamer。', downloadDR: '下载 DesktopRenamer', orDR: '或', copyDR: '复制' },
        companions: { label: '配套', headingHtml: '完美契合你的<span class="text-editorial gradient-text">工作流。</span>', desktoprenamerTitle: 'DesktopRenamer', desktoprenamerBody: '重命名你的 macOS 空间，重命名你的体验。SpaceSwitcher 的前置。', optclickerTitle: 'OptClicker', optclickerBody: '用 Option 键实现右键点击。一款简单实用工具，配合你的 macOS 工作流使用。', learnMore: '了解更多' },
        footer: { copyright: '© 2026 - Michael Qiu.', brand: 'SpaceSwitcher.' },
        sidebar: { home: '首页', overview: '概览', features: '功能', install: '安装', companions: '配套', github: 'GitHub' },
        sectionLabels: { home: '首页', overview: '概览', features: '功能', 'more-features': '功能', install: '安装', companions: '配套' }
    }
};
